# Generated by Django 3.2.5 on 2021-09-08 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_alter_blogmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='status',
            field=models.IntegerField(choices=[(1, '未完了'), (2, '作業中'), (3, '完了')], default=1),
        ),
    ]
