# Generated by Django 3.2.5 on 2021-09-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20210908_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='postdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
